# getting base image ubuntu
FROM ubuntu

MAINTAINER francois auxietre <f.auxietre@gmail.com>

RUN apt-get update
RUN apt-get install -y python3.6
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN npm install create-react-app
CMD ["echo", "hello world"]
